/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JJsonnet */

#ifndef _Included_JJsonnet
#define _Included_JJsonnet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JJsonnet
 * Method:    evaluateSnippet
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JJsonnet_evaluateSnippet
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JJsonnet
 * Method:    evaluateFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JJsonnet_evaluateFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
